### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by Lynsir** [JeasunLok/UNet-pytorch#1]
这个项目能够正常运行吗？我运行发现了不少问题

**Comment by JeasunLok** [comment]
项目重构之后还没有进行测试，等我过段时间闲下来再维护一下，感谢理解

**Comment by JeasunLok** [comment]
现在应该可以正常运行了，如果还有问题欢迎提出

**Comment by Lynsir** [comment]
好的，让我看看你的思路，我自己也调通了一版，但准确率是100%让我很疑惑
