### ISSUE TITLE
咨询Val_Epoch与test_Epoch中出现的nan值问题

### ISSUE THREAD

**Issue by Candy-CY** [JeasunLok/UNet-pytorch#2]
不知道博主是否遇到过这类问题，本人尝试再分母中加入常数避免分母为0的情况。
![微信图片_20241107112914](https://github.com/user-attachments/assets/560e8077-def4-4f7c-9b2a-c842a6a26551)

W-Recall: nan li-Precision: nani-F1: nan

**Comment by JeasunLok** [comment]
不知道你是不是用的我提供的数据，如果你用的是我提供的数据，然后ignore_index设置成-1，应该是没问题的，你可以在utils/utils.py下看看这三个指标的计算代码：
```
def compute_metrics(CM, ignore_index=-1):
    np.seterr(divide="ignore", invalid="ignore")
    if ignore_index >= 0:
      CM = np.delete(CM, ignore_index, axis=0)
      CM = np.delete(CM, ignore_index, axis=1)
    num_classes = CM.shape[0]
    GT_array = np.sum(CM, axis=0)
    TP_array = np.diag(CM)
    Recall_array = np.array([])
    Precision_array = np.array([])
    F1_array = np.array([])
    for i in range(num_classes):
        TP = TP_array[i]
        FP = np.sum(CM[i,:])-TP
        FN = np.sum(CM[:,i])-TP
        TN = np.sum(CM)-TP-FP-FN
        # print(i, TP, FP, FN, TN)
        Recall = TP/(TP+FN)
        Precision = TP/(TP+FP)
        F1 = 2*Recall*Precision/(Recall+Precision)
        Recall_array = np.append(Recall_array, Recall)
        Precision_array = np.append(Precision_array, Precision)
        F1_array = np.append(F1_array, F1)
    # print(Recall_array, Precision_array, F1_array)
    weighted_Recall = np.sum(GT_array*Recall_array)/np.sum(CM)
    weighted_Precision = np.sum(GT_array*Precision_array)/np.sum(CM)
    weighted_F1 = np.sum(GT_array*F1_array)/np.sum(CM)
    
    return weighted_Recall, weighted_Precision, weighted_F1
```
如果用的是自己的数据集，需要测试一下自己数据是不是有问题，比如标签多了些东西

**Comment by Candy-CY** [comment]
好的，谢谢您的解答，我用的是自己的数据集，标签的处理应该是没有问题的，我后续再仔细研究一下代码，看看具体是哪里出现了问题！非常感谢！🌹



在 2024-11-07 17:07:42，"JeasunLok" ***@***.***> 写道：

不知道你是不是用的我提供的数据，如果你用的是我提供的数据，然后ignore_index设置成-1，应该是没问题的，你可以在utils/utils.py下看看这三个指标的计算代码：
`def compute_metrics(CM, ignore_index=-1):
np.seterr(divide="ignore", invalid="ignore")
if ignore_index >= 0:
CM = np.delete(CM, ignore_index, axis=0)
CM = np.delete(CM, ignore_index, axis=1)
num_classes = CM.shape[0]
GT_array = np.sum(CM, axis=0)
TP_array = np.diag(CM)
Recall_array = np.array([])
Precision_array = np.array([])
F1_array = np.array([])
for i in range(num_classes):
TP = TP_array[i]
FP = np.sum(CM[i,:])-TP
FN = np.sum(CM[:,i])-TP
TN = np.sum(CM)-TP-FP-FN
# print(i, TP, FP, FN, TN)
Recall = TP/(TP+FN)
Precision = TP/(TP+FP)
F1 = 2RecallPrecision/(Recall+Precision)
Recall_array = np.append(Recall_array, Recall)
Precision_array = np.append(Precision_array, Precision)
F1_array = np.append(F1_array, F1)
# print(Recall_array, Precision_array, F1_array)
weighted_Recall = np.sum(GT_arrayRecall_array)/np.sum(CM)
weighted_Precision = np.sum(GT_arrayPrecision_array)/np.sum(CM)
weighted_F1 = np.sum(GT_array*F1_array)/np.sum(CM)

return weighted_Recall, weighted_Precision, weighted_F1`


如果用的是自己的数据集，需要测试一下自己数据是不是有问题，比如标签多了些东西

**Comment by JeasunLok** [comment]
嗯嗯，有问题随时提issue就好
